// Import icons
import point from "../../assets/icons/point.svg";
import star from "../../assets/icons/star.svg";

// Import slide images
import slide1 from "../../assets/img/slide1.jpg";
import slide2 from "../../assets/img/slide2.jpg";
import slide3 from "../../assets/img/slide3.jpg";
import slide4 from "../../assets/img/slide4.jpg";
import slide5 from "../../assets/img/slide5.jpg";

const slides = [
  {
    id: 1,
    img: slide1,
    title: "The Great Wall",
    point: point,
    star: star,
    location: "China",
    rate: "4.9",
    time: "7 Day 8 Nights",
    price: "$850",
    person: "/person",
  },
  {
    id: 2,
    img: slide2,
    title: "Dizin",
    point: point,
    star: star,
    location: "Iran",
    rate: "4.6",
    time: "5 Day 6 Nights",
    price: "$550",
    person: "/person",
  },
  {
    id: 3,
    img: slide3,
    title: "Sajek Valley",
    point: point,
    star: star,
    location: "Bangladesh",
    rate: "4.7",
    time: "3 Day 4 Nights",
    price: "$400",
    person: "/person",
  },
  {
    id: 4,
    img: slide4,
    title: "Osaka Castle",
    point: point,
    star: star,
    location: "Japan",
    rate: "4.7",
    time: "4 Day 5 Nights",
    price: "$700",
    person: "/person",
  },
  {
    id: 5,
    img: slide5,
    title: "Statue of Liberty",
    point: point,
    star: star,
    location: "New York",
    rate: "4.9",
    time: "4 Day 5 Nights",
    price: "$450",
    person: "/person",
  },
  {
    id: 6,
    img: slide1,
    title: "The Great Wall",
    point: point,
    star: star,
    location: "China",
    rate: "4.9",
    time: "7 Day 8 Nights",
    price: "$850",
    person: "/person",
  },
  {
    id: 7,
    img: slide2,
    title: "Dizin",
    point: point,
    star: star,
    location: "Iran",
    rate: "4.6",
    time: "5 Day 6 Nights",
    price: "$550",
    person: "/person",
  },
  {
    id: 8,
    img: slide3,
    title: "Sajek Valley",
    point: point,
    star: star,
    location: "Bangladesh",
    rate: "4.7",
    time: "3 Day 4 Nights",
    price: "$400",
    person: "/person",
  },
  {
    id: 9,
    img: slide4,
    title: "Osaka Castle",
    point: point,
    star: star,
    location: "Japan",
    rate: "4.7",
    time: "4 Day 5 Nights",
    price: "$700",
    person: "/person",
  },
  {
    id: 10,
    img: slide5,
    title: "Statue of Liberty",
    point: point,
    star: star,
    location: "New York",
    rate: "4.9",
    time: "4 Day 5 Nights",
    price: "$450",
    person: "/person",
  },
];

export default slides;
